apiVersion: v1
kind: Service
metadata:
  name: flyio
  labels:
    app: flyio
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: 3000
      port: 3000
      protocol: TCP
  selector:
    app: flyio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyio
  labels:
    app: flyio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flyio
  template:
    metadata:
      labels:
        app: flyio
      name: flyio
    spec:
      containers:
      - name: flyio
        # The $REPOSITORY_URI and $IMAGE_TAG placeholders will be replaced by actual values supplied by the build action in your workflow
        image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flyio
  labels:
    app: flyio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: flyio
            port:
              number: 3000
        path: /app
        pathType: Prefix
